import turtle
screen = turtle.Screen()
turtle.speed(1)
turtle.penup()

turtle.pencolor("black")
turtle.fillcolor("#bc6a3c") # brown color

turtle.begin_fill()
turtle.goto(-80, 9)
turtle.pendown()
turtle.goto(83, 9)
turtle.penup()
turtle.goto(90, 0)
turtle.pendown()
turtle.write(turtle.pos())
turtle.goto(8, 94)
turtle.goto(-80, 9)
turtle.end_fill()

turtle.fillcolor("#5f695e")  # Grey color
turtle.begin_fill()
turtle.penup()
turtle.goto(8, 94)
turtle.pendown()
turtle.goto(0, 100)
turtle.write(turtle.pos())
turtle.goto(-100, 0)
turtle.goto(-80, 2)
turtle.end_fill()

turtle.penup()
turtle.goto(-80, 9)
turtle.pendown()
turtle.goto(8, 94)
turtle.penup()

turtle.fillcolor("#e5e3d9") # Cream color
turtle.goto(88, 9)
turtle.begin_fill()
turtle.goto(88, 0)
turtle.pendown()
turtle.goto(88, -100)
turtle.write(turtle.pos())
turtle.goto(-80, -100)
turtle.write(turtle.pos())
turtle.goto(-80, 9)
turtle.end_fill()

turtle.penup()
turtle.goto(0, 100)
turtle.pendown()
#turtle.goto(250, 150)

turtle.fillcolor("#5f695e")
turtle.begin_fill()
turtle.goto(250, 110)
turtle.write(turtle.pos())
#turtle.goto(350, 50)
turtle.goto(350, 30)
turtle.write(turtle.pos())
turtle.goto(90, 0)
turtle.end_fill()

turtle.penup()
turtle.goto(90, 0)
turtle.fillcolor("#e5e3d9") # Cream color
turtle.begin_fill()
turtle.goto(90, -100)
turtle.pendown()
turtle.goto(340, -50)
turtle.write(turtle.pos())
turtle.goto(340, 30)
turtle.end_fill()

turtle.penup()
turtle.fillcolor("#bc6a3c")
turtle.goto(-30, -30)
turtle.pendown()
turtle.begin_fill()
turtle.goto(-30, -100)
turtle.goto(-1, -100)
turtle.goto(-1, -30)
turtle.end_fill()

turtle.begin_fill()
turtle.goto(1, -30)
turtle.goto(1, -100)
turtle.goto(30, -100)
turtle.goto(30, -30)
turtle.goto(-30, -30)
turtle.end_fill()

turtle.penup()
turtle.goto(-6, -64)
turtle.pendown()
turtle.goto(6, -64)
turtle.goto(6, -66)
turtle.goto(-6, -66)
turtle.goto(-6, -64)
turtle.penup()
turtle.goto(-100, -150)
turtle.pendown()
turtle.goto(-100, -230)
turtle.penup()
turtle.goto(-97, -150)
turtle.pendown()
turtle.circle(-20, 180)
turtle.setheading(0)
turtle.goto(-97, -190)
turtle.circle(-20, 180)
turtle.hideturtle()
turtle.done() 